---

parser: babel-eslint

globals:
  it: true
  expect: true
  describe: true
  test: true
  jest: true

extends:
- plugin:eslint-plugin-import/warnings
- plugin:eslint-plugin-import/errors

plugins:
- flowtype

env:
  jest: true

rules:
  flowtype/require-valid-file-annotation: [2, "always"]
  flowtype/boolean-style: [2, "boolean"]
  flowtype/use-flow-type: 2
